name: Publish VSCode extension

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - run: npm ci
      - run: npm run build-extension
      - name: Publish
        if: startsWith(github.ref, 'refs/tags/')
        run: npm run publish
        env:
          VSCE_PAT: ${{ secrets.PUBLISH_VSCODE_EXTENSION }}
